### ISSUE TITLE
Usage with existing NAPI project

### ISSUE THREAD

**Issue by a7ul** [Geode-solutions/genepi#4]
Hi @BotellaA  and @panquez 
First of all amazing stuff! I was looking for something like this for a long time.

My question is, Can I use this in an existing project that already has N-API ?

For example, I would love to use this for https://github.com/nodegui/nodegui where I have a lot of NAPI wrapped classes. Fortunately, the build system is the same (CMake).

I just wanted to clarify this before I jump in. 
My specific query is:
Can I mix both GENPI and raw NAPI methods in a GENEPI class?

**Comment by BotellaA** [comment]
Hello @master-atul, thanks for your interest in `genepi`.

I see you are also using `node-addon-api` to wrap your classes, so let me detailed more how `genepi` is working. A classical way to wrap a class `Foo` using `node-addon-api` is
```C++
class Foo : public Napi::ObjectWrap<Foo>
```

This cannot be done with `genepi` since we only know the wrapped class type at compiled time. We added an indirection using template mecanism
```C++
class ClassWrapper<Foo> : public Napi::ObjectWrap<ClassWrapper<Foo>>
```

To come back to your question, the only major difference between a raw wrapped class and a genepi class is this indirection. From the C++ side, you have to call the [`get_bound`](https://github.com/Geode-solutions/genepi/blob/master/include/genepi/class_wrapper.h#L78) method to access the `Foo` class and then it is like a raw N-API.

**Comment by BotellaA** [comment]
@master-atul do you need additional information?

**Comment by a7ul** [comment]
No, I ll open a new issue when I need more info. Thanks. Closing it.
